version: '2'

services:
  bdb-driver:
    build:
      context: .
      dockerfile: ./compose/bigchaindb-driver-khyber/Dockerfile
    environment:
      BDB_HOST: bdb-server
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
    command: pytest -v
  rdb:
    image: rethinkdb
    ports:
      - "58585:8080"
      - "28015"

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - .:/etc/nginx/

  bdb-server:
    build: ./compose/bigchaindb-server
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
    ports:
      - "9984"
    command: bigchaindb start

  bdb-server-khyber:
    build:
      context: .
      dockerfile: ./compose/bigchaindb-server-khyber-flask/Dockerfile
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9985
    ports:
      - "9985"
    volumes:
      - ./bigchaindb-khyber:/usr/src/app/bigchaindb-khyber
    command: python bigchaindb-khyber/web/server_flask.py

